# Собираем приложение в отдельном образе
FROM ubuntu:22.04 AS dotnet_build_runtime_image
WORKDIR /src
RUN apt update && \
    apt install -y ca-certificates && \
    update-ca-certificates && \
    apt install -y dotnet-sdk-6.0 && \
	rm -fr /var/lib/apt/lists/*

# Копируем из сходников пока только файлы sln и csproj, сохраняя структуру каталогов,
# это позволит на данном слое закешировать выкачивание всех нужных для приложения пакетов (dotnet restore)
COPY HealthCheckDotNetFive.sln .
COPY HealthCheckDotNetFive/HealthCheckDotNetFive.csproj ./HealthCheckDotNetFive/
RUN dotnet restore

# Теперь уже копируем все исходники и собираем обычную runtime зависимую сборку
COPY . .
RUN dotnet publish --no-restore -c release -o /app

# Итоговый образ
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8000 DOTNET_RUNNING_IN_CONTAINER=true
EXPOSE 8000
COPY --from=dotnet_build_runtime_image /app .
ENTRYPOINT ["dotnet", "/app/HealthCheckDotNetFive.dll"]
